services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bpsdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - budgetplanner-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    container_name: budgetplanner-backend
    build:
      context: ./budgetplannerbackend
      dockerfile: ../BUDGET_PLANNER_FULLSTACK/backend.Dockerfile
    ports:
      - "2099:2099"
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    networks:
      - budgetplanner-network

  frontend:
    container_name: budgetplanner-frontend
    build:
      context: ./budgetplannerfrontend  
      dockerfile: ../BUDGET_PLANNER_FULLSTACK/frontend.Dockerfile
    ports:
      - "2098:80"
    depends_on:
      - backend
    networks:
      - budgetplanner-network

volumes:
  mysql-data:

networks:
  budgetplanner-network:
    driver: bridge
